
total_tokens_processed: 327680000
train_data: results/TinyStories_tokenized/train_flatten.npy
valid_data: results/TinyStories_tokenized/valid_flatten.npy


vocab_size: 10000
batch_size: 256
context_length: 256
use_cuda: true

# arch
nheads: 16
nlayers: 4
rope_theta: 10000
d_model: 512
d_ff: 1344

# lr
lr_max: 5e-4
lr_min: 1e-5
lr_schedule: cosine
warmup: 3000
annealing_iters: 30000
learning_rate: 1e-5

#validation
valid_every: 1000
valid_iters: 100
log_every: 50
save_best_n: 5

#wandb
wandb_project: TinyStories

output_dir: results/training/TinyStories
save_every: 10000